language: node_js
addons:
    chrome: latest
cache:
    directories:
        - ~/.npm
        - node_modules
install:
    - npm install
node_js:
  - "10"
  - "9"
  - "8"
script:
  - npm run lint
  - npm install
  - npm test
