language: node_js
os:
    - linux
addons:
    chrome: stable
cache:
    directories:
        - ~/.npm
        - node_modules
install:
    - npm install
node_js:
  - "10"
  - "12"
script:
  - npm run lint
  - npm install
  - npm test
