version: 1
update_configs:
    - package_manager: "javascript"
      directory: "/src/templates/apify_project"
      update_schedule: "live"
      default_reviewers:
         - "drobnikj"
    - package_manager: "javascript"
      directory: "/src/templates/basic_crawler"
      update_schedule: "live"
      default_reviewers:
        - "drobnikj"
    - package_manager: "javascript"
      directory: "/src/templates/cheerio_crawler"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
    - package_manager: "javascript"
      directory: "/src/templates/hello_world"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
    - package_manager: "javascript"
      directory: "/src/templates/puppeteer_crawler"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
    - package_manager: "javascript"
      directory: "/src/templates/puppeteer_single_page"
      update_schedule: "live"
      default_reviewers:
          - "drobnikj"
